apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-workflow-sample
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: app
          env:
            - name: ENV
              value: prd
